fragment ImageFragment on FileFieldInterface {
	id
	width
	height
	alt
	basename
	format
	mimeType
	size
	title
	url
	focalPoint {
		x
		y
	}
	responsiveImage(
		imgixParams: { auto: format, w: 1920, h: 1080, fit: crop }
		sizes: "(max-width: 46.24em) 50vw, 25vw"
	) {
		width
		height
		alt
		aspectRatio
		base64
		bgColor
		sizes
		src
		srcSet
		webpSrcSet
		title
	}
}
